//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top2000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_YearList_User
    {
        public Nullable<int> Track_TrackId { get; set; }
        public string Users_UserName { get; set; }
        public Nullable<int> YearList_YearListId { get; set; }
        public int Id { get; set; }
    
        public virtual Tracks Tracks { get; set; }
        public virtual YearList YearList { get; set; }
    }
}
